packages:
  - "packages/*"
  - "packages/*/*" # 支持两层嵌套的子包
  - playground
  # exclude packages that are inside test directories
  - "!**/test/**"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
